#!/bin/bash
echo "\t*********UPDATE*********\n" > /var/log/update_script.log
apt-get update -y >> /var/log/update_script.log
echo "\n\t*********UPGRADE*********\n" >> /var/log/update_script.log
apt-get upgrade -y >> /var/log/update_script.log
echo "\n\t*********DIST-UPGRADE*********\n" >> /var/log/update_script.log
apt-get dist-upgrade -y >> /var/log/update_script.log
