#!/bin/bash
# Vaciar tablas actuales
sudo iptables -t filter -F

# Vaciar reglas personales
sudo iptables -t filter -X

# Prohibir todas las conexiones entrantes y salientes
sudo iptables -t filter -P INPUT DROP
sudo iptables -t filter -P OUTPUT DROP
sudo iptables -t filter -P FORWARD DROP

# No romper conexiones ya establecidas
sudo iptables -t filter -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
sudo iptables -t filter -A OUTPUT -m state --state RELATED,ESTABLISHED -j ACCEPT

# Autorizar loopback
sudo iptables -t filter -A INPUT -i lo -j ACCEPT
sudo iptables -t filter -A OUTPUT -o lo -j ACCEPT

# ICMP (Ping)
sudo iptables -t filter -A INPUT -p icmp -j ACCEPT
sudo iptables -t filter -A OUTPUT -p icmp -j ACCEPT

# SSH In
sudo iptables -t filter -A INPUT -p tcp --dport 452 -j ACCEPT

# SSH Out
sudo iptables -t filter -A OUTPUT -p tcp --dport 452 -j ACCEPT

# DNS In/Out
sudo iptables -t filter -A OUTPUT -p tcp --dport 53 -j ACCEPT
sudo iptables -t filter -A OUTPUT -p udp --dport 53 -j ACCEPT
sudo iptables -t filter -A INPUT -p tcp --dport 53 -j ACCEPT
sudo iptables -t filter -A INPUT -p udp --dport 53 -j ACCEPT

# NTP Out
sudo iptables -t filter -A OUTPUT -p udp --dport 123 -j ACCEPT

# HTTP + HTTPS Out
sudo iptables -t filter -A OUTPUT -p tcp --dport 80 -j ACCEPT
sudo iptables -t filter -A OUTPUT -p tcp --dport 443 -j ACCEPT

# HTTP + HTTPS In
sudo iptables -t filter -A INPUT -p tcp --dport 80 -j ACCEPT
sudo iptables -t filter -A INPUT -p tcp --dport 443 -j ACCEPT
sudo iptables -t filter -A INPUT -p tcp --dport 8443 -j ACCEPT

# FTP Out
sudo iptables -t filter -A OUTPUT -p tcp --dport 20:21 -j ACCEPT

# FTP In
sudo modprobe ip_conntrack_ftp # ligne facultative avec les serveurs OVH
sudo iptables -t filter -A INPUT -p tcp --dport 20:21 -j ACCEPT
sudo iptables -t filter -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT


## NULL-SCAN
/sbin/iptables -t filter -A INPUT -p tcp --tcp-flags ALL NONE -j LOG \
			--log-prefix "NULL-SCAN: [FIREWALL ALERT]"
/sbin/iptables -t filter -A INPUT -p tcp --tcp-flags ALL NONE -j DROP

## XMAS-SCAN
/sbin/iptables -t filter -A INPUT -p tcp --tcp-flags ALL ALL -j LOG \
			--log-prefix "XMAS-SCAN: [FIREWALL ALERT]"
/sbin/iptables -t filter -A INPUT -p tcp --tcp-flags ALL ALL -j DROP

## SYNFIN-SCAN
/sbin/iptables -t filter -A INPUT -p tcp --tcp-flags ALL SYN,FIN -j LOG \
			--log-prefix "SYNFIN-SCAN: [FIREWALL ALERT]"
/sbin/iptables -t filter -A INPUT -p tcp --tcp-flags ALL SYN,FIN -j DROP

## NMAP-XMAS-SCAN
/sbin/iptables -t filter -A INPUT -p tcp --tcp-flags ALL URG,PSH,FIN -j LOG \
			--log-prefix "NMAP-XMAS-SCAN: [FIREWALL ALERT]"
/sbin/iptables -t filter -A INPUT -p tcp --tcp-flags ALL URG,PSH,FIN -j DROP

## FIN-SCAN
/sbin/iptables -t filter -A INPUT -p tcp --tcp-flags ALL FIN -j LOG \
			--log-prefix "FIN-SCAN: [FIREWALL ALERT]"
/sbin/iptables -t filter -A INPUT -p tcp --tcp-flags ALL FIN -j DROP

## NMAP-ID
/sbin/iptables -t filter -A INPUT -p tcp --tcp-flags ALL URG,PSH,SYN,FIN -j LOG \
			--log-prefix "NMAP-ID: [FIREWALL ALERT]"
/sbin/iptables -t filter -A INPUT -p tcp --tcp-flags ALL URG,PSH,SYN,FIN -j DROP

## SYN-RST
/sbin/iptables -t filter -A INPUT -p tcp --tcp-flags SYN,RST SYN,RST -j LOG \
			--log-prefix "SYN-RST: [FIREWALL ALERT]"
/sbin/iptables -t filter -A INPUT -p tcp --tcp-flags SYN,RST SYN,RST -j DROP

## SYN-FLOODING
/sbin/iptables -t filter -N syn-flood
/sbin/iptables -t filter -A INPUT -i ens33 -p tcp --syn -j syn-flood
/sbin/iptables -t filter -A syn-flood -m limit --limit 1/sec --limit-burst 4 -j RETURN
/sbin/iptables -t filter -A syn-flood -j LOG \
			--log-prefix "SYN-FLOOD: [FIREWALL ALERT]"
/sbin/iptables -t filter -A syn-flood -j DROP

## Make sure NEW tcp connections are SYN packets
/sbin/iptables -t filter -A INPUT -i ens33 -p tcp ! --syn -m state --state NEW -j LOG  \
			--log-prefix "SYN-FLOOD: [FIREWALL ALERT]"
/sbin/iptables -t filter -A INPUT -i ens33 -p tcp ! --syn -m state --state NEW -j DROP

## Port scanner
/sbin/iptables -t filter -N port-scan
#/sbin/iptables -t filter -A INPUT -i $INTERFACE -p tcp --tcp-flags SYN,ACK,FIN,RST RST -j port-scan
/sbin/iptables -t filter -A INPUT -i ens33  -p tcp --tcp-flags SYN,ACK,FIN,RST RST -j port-scan
/sbin/iptables -t filter -A port-scan -m limit --limit 1/s --limit-burst 4 -j RETURN
/sbin/iptables -t filter -A port-scan -j LOG \
			--log-prefix "PORT-SCAN: [FIREWALL ALERT]"
/sbin/iptables -t filter -A port-scan -j DROP

echo 1 > /proc/sys/net/ipv4/tcp_syncookies
echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6
echo 0 > /proc/sys/net/ipv4/ip_forward
echo 1 > /proc/sys/net/ipv4/conf/all/log_martians
echo 1 > /proc/sys/net/ipv4/icmp_ignore_bogus_error_responses
echo 1 > /proc/sys/net/ipv4/conf/all/rp_filter
echo 0 > /proc/sys/net/ipv4/conf/all/send_redirects
echo 0 > /proc/sys/net/ipv4/conf/all/accept_source_route
echo 0 > /proc/sys/net/ipv4/conf/all/accept_redirects
echo 1 > /proc/sys/net/ipv4/icmp_echo_ignore_all
